### ISSUE TITLE
problem with using Involt framework

### ISSUE THREAD

**Issue by pipiHuang** [Involt/Involt#26]
Hi,
I have problem with using Involt framework.
I have read getting start page and followed this example  http://involt.github.io/examples/ex1.html

But when I run the app, my LED can't blink at all.
I download the source code from github, here is the things I have did: 
  add this line to `index.html`: `<div class="ard toggle D5 0">D5</div>`
  in `involt.js`, I change `defaultSerialPort` from `COM7` to `COM3`(my localside comport number)
  and in `involt.ino`, I just modified this part like this:
  ```
...
void setup() {
  Serial.begin(115200);
  pinMode(5, OUTPUT);
}

void loop() {  
  //receive data from your app
  chromeReceive();
  
  digitalWrite(5, chromeDigital[5]);
  
  //send data to your app
  chromeSend();
}
...
```

when I launch my app, I can see comport selection page and choose COM3 to connect.
But no matter how I click the button, my LED can't blink at all.
There are no error message and I don't know where to see console message or serial message.
(I try to push F12 to open console but no message there)

my chrome browser's version is 40.0.2214.115 m
and I use Arduino UNO R3
Can you give me some suggestions? Thanks very much.

**Comment by AlbertSanIza** [comment]
I have the same problem, I noticed that the serial connection is not doing correctly with the current involt.js file.

You should give it a try to the Dev branc to see if it works, if not...  hope @ErniW gets on this soon.

**Comment by ErniW** [comment]
Hi, 

Currently most problems with serial connection are fixed in Dev version (The dev version in my opinion is done but requires additional testing to make sure that connection issues are removed). You should try it if you want. Keep in mind that there are small changes in syntax and how Arduino sketch works.

PS The documentation of new version is almost ready and I want to upload it with new website. The problem is that I don't have free time to finish it :/

**Comment by AlbertSanIza** [comment]
Its ok my friend, 

But I think you should update what you have, community is here to help you, even if we are only 3 right now, this will be a huge project! so cheer up :dancers: 

I'll be expecting the new changes.

**Comment by pipiHuang** [comment]
OK, thanks for reply.
I already download the dev version and still try it.
I am beginner of javascript so I may have to cost more time to understand how to use new version.
I sincerely hope the document of new version can update in github as soon as possible.
Thanks a lot.

**Comment by ErniW** [comment]
To see the console log right click on app and click inspect element
instead of inspect background page.

![involtans](https://cloud.githubusercontent.com/assets/6878351/6376473/4df01d38-bd1e-11e4-8491-53047a6fb063.png)

**Comment by pipiHuang** [comment]
Thanks. I can see the console log now.
Now I can connect potentiometer to pin A0 show value from pin A0.
But I still can't send signal to to control LED blink.

**Comment by ErniW** [comment]
Hmmm maybe try to change `boolean directMode` to false when having `digitalWrite` in loop. Or keep it true and remove `digitalWrite` (There are two modes that involt uses to receive data from chrome to arduino).

**Comment by pipiHuang** [comment]
I have already change `boolean directMode` to false(in `involt.ino` file).
I add button into index.html, like this:
```
<div class="ard toggle D5 0"></div>
```
or this :
```
<div class="ard button P5 40">Turn me ON</div>
<div class="ard button P5 0">Turn me OFF</div>
```
In short, I follow this example: http://involt.github.io/examples/ex1.html

On the other hand, this example can work fine: http://involt.github.io/examples/ex2.html
That seems like my app can receive data form Arduino, but my app can't send data to Arduino (I can't control LED by click button of my app)

**Comment by pipiHuang** [comment]
I have solved the problem. sometimes connection will failed.

**Comment by ErniW** [comment]
Ok. Good job!

Now involt has a new documentation and website. I can close this issue.

Thanks
